import { Shield, Users, Bot, Scale, BookOpen } from "lucide-react";

export const digitalModules = [
  {
    icon: Shield,
    title: "🛡️ An Toàn Số",
    description: "Thành cao thủ phòng thủ! Học cách nhận biết lừa đảo, bảo vệ thông tin cá nhân và tài khoản ngân hàng an toàn tuyệt đối",
    color: "bg-gradient-to-br from-red-100 to-orange-100 text-red-700",
    gradient: "from-red-500 to-orange-500",
    level: "Cơ bản",
    badge: "Thiết yếu",
    stats: "15+ bài học",
    duration: "2-3 tuần",
    difficulty: 1,
    link: "/scam-types",
  },
  {
    icon: Users,
    title: "💝 Đạo Đức Số",
    description: "Trở thành công dân số văn minh! Nắm vững quy tắc ứng xử online, giao tiếp tích cực và xây dựng cộng đồng mạng lành mạnh",
    color: "bg-gradient-to-br from-purple-100 to-pink-100 text-purple-700",
    gradient: "from-purple-500 to-pink-500",
    level: "Cơ bản",
    badge: "Quan trọng",
    stats: "12+ bài học",
    duration: "2 tuần",
    difficulty: 1,
    link: "/digital-ethics",
  },
  {
    icon: Bot,
    title: "🤖 AI An Toàn",
    description: "Làm chủ công nghệ AI! Sử dụng thông minh, nhận biết deepfake và nội dung giả mạo, đón đầu xu hướng công nghệ",
    color: "bg-gradient-to-br from-blue-100 to-cyan-100 text-blue-700",
    gradient: "from-blue-500 to-cyan-500",
    level: "Nâng cao",
    badge: "Trending",
    stats: "20+ bài học",
    duration: "3-4 tuần",
    difficulty: 3,
    link: "/ai-safety",
  },
  {
    icon: Scale,
    title: "⚖️ Pháp Luật Số",
    description: "Hiểu biết pháp lý số! Nắm rõ bản quyền, sở hữu trí tuệ, chia sẻ hợp pháp và bảo vệ quyền lợi của bạn trong thế giới số",
    color: "bg-gradient-to-br from-indigo-100 to-blue-100 text-indigo-700",
    gradient: "from-indigo-500 to-blue-500",
    level: "Trung bình",
    badge: "Cần thiết",
    stats: "18+ bài học",
    duration: "3 tuần",
    difficulty: 2,
    link: "/digital-law",
  },
  {
    icon: BookOpen,
    title: "💻 Kỹ Năng Số",
    description: "Thành thạo kỹ năng số! Digital literacy, công cụ collaboration hiện đại và nâng cao năng suất làm việc trong kỷ nguyên 4.0",
    color: "bg-gradient-to-br from-green-100 to-emerald-100 text-green-700",
    gradient: "from-green-500 to-emerald-500",
    level: "Thực hành",
    badge: "Hot",
    stats: "25+ bài học",
    duration: "4-5 tuần",
    difficulty: 2,
    link: "/digital-skills",
  },
];
